### ISSUE TITLE
commands or arguments for selection

### ISSUE THREAD

**Issue by Vardelm** [brittyazel/Neuron#376] opened 2020-10-30 23:34 UTC
## Is your feature request related to a problem? Please describe:
I set up my action bars to mimic the keyboard with key shortcuts, drag abilities to the key I want to use, and then hide the bar so that I have a very clean UI.  I have a macro to toggle display of the 1 action bar: /neuron conceal.  However, any time I log in or reload the UI, I have to manually go to edit mode, select the bar, and then get out of edit mode because the command only works on the selected bar.  It works, but can be a hassle.

## Describe the solution you'd like to see implemented:
Preferably, I'd like to have arguments to the various commands for which bar they apply to, so for conceal you might have:

/neuron conceal barName1 barName2 ... etc.

This would allow multiple bars to be changed w/ 1 command.   However, if that's too much work, I could easily get by for now if there were just a slash command for selecting a particular bar:

/neuron select barName1

Since I'm only using 1 action bar (see below), a select command would work.  I don't know if you could use multiple select commands in 1 macro, such as:

/neuron select barName1
/neuron conceal
/neuron select barName2
/neuron conceal

If not and the arguments method is too much work, I'd go for just the select command and wait for the other structural changes being made to the addon.

## Describe alternatives you've considered:
I have used Dominos, Bartender, Macaroon, Button Forge, & more.  In all of those I was able to make a macro to show/hide bars.  The reason I'd like to use Neuron is because of how it handles bars & druid forms.  I can have 1 bar that completely changes for each form.  AWESOME!   If being able to show/hide bars is a little easier, I'm a convert.

## Additional context:
For context, this shows the 1 bar I have set up in Neuron.  During gameplay, it's hidden.

![WoWScrnShot_103020_164148](https://user-images.githubusercontent.com/73724121/97764994-dc8d9a80-1ae6-11eb-9904-f5882c0e08da.jpg)

![Uploading WoWScrnShot_103020_164132.jpg…]()

**Comment by brittyazel** [comment] 2021-05-02 00:32
I added this a while back, sorry for never closing this issue. Is this working for you as intended?

**Closed by brittyazel** 2021-05-02 00:32 UTC
Labels: enhancement

**Comment by Vardelm** [comment] 2021-05-02 14:50
Yep, works perfect!  Thank you!

No problem on the timing at all.  Glad you were able to add this!
