### ISSUE TITLE
Pet battle interface issue

### ISSUE THREAD

**Issue by Keshk1** [brittyazel/Neuron#115] opened 2018-06-17 04:41 UTC
When I started doing pet battles recently, the menu bar items showed up in the interface.  With the menu bar changes, something in Neuron is blocking this from happening.  I tried it with all my pet battle addons disabled and it still occurred so I disabled Neuron too and it reappeared in the interface.

![no pet addons neuron off](https://user-images.githubusercontent.com/40329850/41504742-e38f5204-71ad-11e8-9940-51a21da80de5.jpg)
![no pet addons neuron on](https://user-images.githubusercontent.com/40329850/41504743-eef6cab4-71ad-11e8-8850-89bc080ab915.jpg)

Hoping the screenshots work correctly.

**Comment by brittyazel** [comment] 2018-06-17 06:06
Yeah the pet battle interface was stealing the buttons away from Neuron, so if there is a Neuron Menu Bar created, I stop the pet battle interface from using the menu bar. Is this a problem for you? Can you explain more about what the issue is?

**Comment by Keshk1** [comment] 2018-06-17 07:38
I like to be able to pull up the "Collections" panel when I am battling wild pets if a rare pops up to see if I have that breed or level. I might be able to figure out how to do the same thing via one of the pet addons.

**Comment by Keshk1** [comment] 2018-06-17 07:39
Oops, wrong button.

**Comment by brittyazel** [comment] 2018-06-17 17:33
Where is your normal menu bar? All of those buttons exist on the normal Neuron Menu Bar, but I don't see it in your screenshot

**Comment by Keshk1** [comment] 2018-06-17 17:46
During pet battles, the normal UI is closed.  The menu bar is on the right side of the pet interface "box" in the picture with no addons at all.  That box is empty with Neuron on.  That is probably why it "steals" the buttons because the pet battle interface is actually a separate UI and pulls the buttons from the standard UI.  Just guessing here.

**Comment by brittyazel** [comment] 2018-06-17 17:51
oooh I see now. Yes, you're right. This may be tricky

**Comment by Keshk1** [comment] 2018-06-17 17:53
No rush on it, just wanted you to be aware more than anything.  BTW, thanks for all the hard work and keeping this going.  Every time it looked like this died, my heart sank because it is the on bar addon that has ever really worked for me.

**Comment by brittyazel** [comment] 2018-06-17 19:30
Ugh I looked at this for the past hour, and I honestly don't know what to do. I can probably figure something out so that the Neuron Menu Bar doesn't hide with the rest of the UI. This is already pretty messy though. There's just no way right now that I can release all the buttons back to blizzard cleanly.

The stupid thing is that the blizzard default code assumes that all the menu buttons are anchored to eachother, thus when they move for the pet battle interface it only actually moves the first button in each of the new rows. However, since our buttons aren't anchored to eachother but rather to the center of the invisible Neuron wrapper buttons, the only buttons that move over are the Character Button and the LFD Button...ugh!

**Comment by brittyazel** [comment] 2018-12-15 07:49
Ok this is fixed now. I intercepted the call that pulls the buttons back in to the pet battle frame, and on the fly we now overwrite this function to put the buttons back on top of the pet battle frame manually. Enjoy!

**Closed** 2018-12-15 07:49 UTC
