### ISSUE TITLE
Vehicle Bar Bug in German Version

### ISSUE THREAD

**Issue by Soliii** [brittyazel/Neuron#19] opened 2017-12-08 19:18 UTC
When i claim a Vehicle, the buttons are in the Petbar. No Makrobuttons on it. So its terrible to move and fight in a Vehicle

https://abload.de/img/neuebitmap51sulp.jpg
https://abload.de/img/neuebitmap3434yusbe.jpg

English Client works perfect. Maybee translation Bug. I use a German Client

**Comment by brittyazel** [comment] 2017-12-09 21:02
So you tested the English client and the big isn't present?

**Comment by brittyazel** [comment] 2017-12-09 21:02
Bug*

**Comment by brittyazel** [comment] 2017-12-13 06:21
I'm looking to figure out this issue, but i'm still having a hard time. Mostly because I don't speak any German. However, this bug could be due to the German translations being pretty terrible.

That being said, if you would like to help with the German translations, I would be hugely grateful. I have been trying to refresh the German translations to match the English translations, but it's slow going as I'm just using Google Translate.
https://github.com/brittyazel/Neuron/blob/master/Localizations/Neuron_X-deDE.lua

**Comment by brittyazel** [comment] 2018-01-02 01:24
You said the latest version was fixed with the translation updates. Glad to see that the problem is resolved!

**Closed by brittyazel** 2018-01-02 01:24 UTC
Labels: bug, good first issue, help wanted
