### ISSUE TITLE
Extra Action Button staying visible

### ISSUE THREAD

**Issue by Trajin** [brittyazel/Neuron#278] opened 2019-02-11 03:55 UTC
i've noticed this issue lately where the extra action button will stay visible after completing the quest that is using it.   Today was the invasions in Tiragard sound.   The jetpack was using the button.  After completing that quest, the button would still show.
It only happened on two characters though.   I ran at least 12 toons through world quests today and it only happened twice and /reload cleared it up.
Since it's so intermittent, I won't know if this latest version will fix it.   i just saw the latest version on wowinterface so I'll try that this week to see if it works.

**Comment by brittyazel** [comment] 2019-02-11 04:12
Yeah I've noticed that as well, buy I could NOT figure out why. I need to find a pattern before I can fix that one

**Comment by raysmith59** [comment] 2019-02-17 23:04
I've seen this occasionally as well and it usually flickers, it's not on stably, at least for me.

**Comment by brittyazel** [comment] 2019-03-08 03:43
Is this still happening. I can't make it happen

**Comment by Trajin** [comment] 2019-03-08 13:19
I saw it happen the other day while doing a wold quest but I don’t remember which character i was on.  I don’t think it happens as often now

Sent from my iPhone

On Mar 7, 2019, at 9:44 PM, Britt Yazel <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still happening. I can't make it happen

**Comment by Trajin** [comment] 2019-03-10 22:42
It happened again this morning when running a world quest.

Sent from my iPhone

On Mar 8, 2019, at 4:41 PM, Britt Yazel <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #278<https://github.com/brittyazel/Neuron/issues/278>.

**Comment by raysmith59** [comment] 2019-03-12 00:41
It's still happening, yes.  One thing I noticed with one particular world quest (the assault one where you use the extra action button to reveal hidden horde spies in Arom's Stand) is that when the button SHOULD be showing and active it has a gold border around it (which I'd still like to be able to get rid of :) ), when it's showing incorrectly it has a grey monochrome border of a similar/the same style.  Maybe that means something from the code side?

**Comment by teh-fixerer** [comment] 2019-03-12 01:52
Hopefully I'm not butting in here, but it kind of sounds like the zone button is somehow interfering (might explain seeing a gold border).  maybe separate the zone button and the extra action to be out of the way of each other.  I have mine lined up over vertically spaced apart.  if you are able to reproduce the problem and get a screen shot it may help troubleshoot the problem.
    On Monday, March 11, 2019, 6:41:58 p.m. CST, raysmith59 <notifications@github.com> wrote:  
 
 
It's still happening, yes. One thing I noticed with one particular world quest (the assault one where you use the extra action button to reveal hidden horde spies in Arom's Stand) is that when the button SHOULD be showing and active it has a gold border around it (which I'd still like to be able to get rid of :) ), when it's showing incorrectly it has a grey monochrome border of a similar/the same style. Maybe that means something from the code side?

**Comment by raysmith59** [comment] 2019-03-12 02:26
I do have them separated, quite often in previous expansion content both are active simultaneously so they can't really be put on top of each other.  To be clear, when the frame is grey the button is there, it just doesn't do anything when clicked.  It's not a different button, it's the same one.  Interestingly, though, you may be on to something... it seemed to me that the grey frame was a bit simpler than the gold one, at this point based on the screenshot I just took I'm about 80% certain that it was the Extra Action Button frame (the top one in my screenshot below) that was showing up where the Zone Action Button is along with the actual Zone Action Button itself.  It was in the same location as the ZAB but was flashing back and forth between the two in the active quest area.  If it happens again of course I'll follow up but the easily duplicated scenario requires an assault in Drustvar and the next of those is scheduled for late Thu and that assumes that particular quest is up.

Going out on a limb - any chance in the code there's an accidental reference to EAB instead of ZAB in the ZAB section?  That could start to explain what I think I was seeing.

![image](https://user-images.githubusercontent.com/2917594/54170229-3d68ea80-444c-11e9-8c80-92d5d73fd21b.png)

**Comment by brittyazel** [comment] 2019-03-12 04:49
@rayamith59 I don't think so no. Since I rewrote those sections the code is now super compact. The issue has to be with the SetObjectVisibility() function in the extra action button class, but the thing that I don't understand is how that issue is so transient and how it only applies to a couple of quests. I'll do some more digging to see if I can add a double safety check or something, the real question is figuring out what makes these specific quests different than the rest

**Comment by raysmith59** [comment] 2019-03-13 18:29
I'm encountering this issue now although in this case it's the extra action button in both cases, the quest is Stop the Shipments in Vol'dun during an assault.

Here's when I'm in the quest zone:
![image](https://user-images.githubusercontent.com/2917594/54304636-fab62800-459b-11e9-8296-102bf6e1fa24.png)

Here's when I'm not (different toon, by the time I notice the issue I'm usually done the original quest):
![image](https://user-images.githubusercontent.com/2917594/54304734-2cc78a00-459c-11e9-9234-55e5181d685b.png)

It was flickering at the time when I was out of the quest area.

**Comment by brittyazel** [comment] 2019-03-13 18:34
Interesting. So it seems like the function we use to check if we have an extra ability is erroneously reporting true during these assaults. I'll have to find a new method, as then proper blizzard way seems unreliable at best. Lovely.

**Comment by Trajin** [comment] 2019-03-13 18:40
I see it after azerite wounds or absorption world quests.

Slightly off topic, but would it be possible to have that button without the textures on the sides or is that a blizzard thing?

Sent from my iPhone

On Mar 13, 2019, at 1:29 PM, raysmith59 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm encountering this issue now although in this case it's the extra action button in both cases, the quest is Stop the Shipments in Vol'dun during an assault.

Here's when I'm in the quest zone:
[image]<https://user-images.githubusercontent.com/2917594/54304636-fab62800-459b-11e9-8296-102bf6e1fa24.png>

Here's when I'm not (different toon, by the time I notice the issue I'm usually done the original quest):
[image]<https://user-images.githubusercontent.com/2917594/54304734-2cc78a00-459c-11e9-9234-55e5181d685b.png>

It was flickering at the time when I was out of the quest area.

**Comment by brittyazel** [comment] 2019-03-13 18:43
@trajin it's absolutely possible, I just have to wire in a GUI option for it which I was hoping to avoid with the current God aweful you code. However since the new GUI is still a ways out because I just don't have time right now, I could out an option like that in

**Comment by Trajin** [comment] 2019-03-13 19:17
That would be great if you are able.  Im sure im not the only one that would appreciate it.

Sent from my iPhone

On Mar 13, 2019, at 1:44 PM, Britt Yazel <notifications@github.com<mailto:notifications@github.com>> wrote:


@Trajin<https://github.com/Trajin> it's absolutely possible, I just have to wire in a GUI option for it which I was hoping to avoid with the current God aweful you code. However since the new GUI is still a ways out because I just don't have time right now, I could out an option like that in

**Comment by raysmith59** [comment] 2019-03-13 19:30
Huh - actually thought I'd put in a request for that (a while back there was a GUI option to disable the border feature for one of the two buttons but not the other but at some point it was removed from the one that had it) but I can't find it now.  Alternatively, I used to run add-ons that were supposed to remove the borders from those buttons , is there a way within Neuron to honour settings from other add-ons (ie. is there some sort of global showborder type function that you can leverage rather than making it a config option within Neuron itself)?

**Comment by raysmith59** [comment] 2019-03-13 19:32
In terms of the residual action buttons, most of my recent experiences have been with assaults but I think most of my WQs with those action buttons have been from those, I don't think the issue is limited to assault quests.  I'll provide updates as I come across it again.

**Comment by brittyazel** [comment] 2019-03-14 20:25
@raysmith59 @Trajin Ok I just added the option to disable the border graphics for you guys lol. It will be in the next minor release out later today

**Comment by raysmith59** [comment] 2019-03-14 20:59
<3  :)

**Comment by raysmith59** [comment] 2019-04-22 00:27
Been a while but this issue just happened again with the feather ability after Ji-Kun in Throne of Thunder, was running 25 Heroic and the Extra Action Button for the feather is still hanging around (and flickering) after I'd run a couple of other raids.

**Comment by Hardbunny** [comment] 2019-05-25 02:55
Nighthold going into P3 where this button fades:
https://giant.gfycat.com/BouncyDeadlyAsiaticmouflon.webm

Spires of Arak zone ability after teleporting away:
https://giant.gfycat.com/BlissfulTartIchidna.webm

**Comment by brittyazel** [comment] 2019-05-25 07:54
I need to figure out what all of these occurrences have in common to work around them. Hang tight for a little while, im deep in a huge rewrite of nearly1/2 the add-on including a brand new GUI. I wanna see this big code rewrite through first, because it's going to make everything easy going forward

**Comment by brittyazel** [comment] 2019-09-16 22:25
Ok I did some exploring and found that it is logic in the addon, not a bug with the condition check. I've added a bunch of re-logic to the whole of the addon for showing/hiding butttons, and I'm hoping I can piggyback off that work to fix this one once and for all.

**Comment by brittyazel** [comment] 2020-03-26 04:57
I did it! It's fixed! It's actually. Genuinely. Fixed. Holy effing shit.

**Closed by brittyazel** 2020-03-26 04:57 UTC

**Comment by Trajin** [comment] 2020-03-26 13:36
Great work!   Thank you

Sent from my iPhone

On Mar 25, 2020, at 11:58 PM, Britt Yazel <notifications@github.com> wrote:

﻿

I did it! It's fixed! It's actually. Genuinely. Fixed. Holy effing shit.
