### ISSUE TITLE
New b version: Keybind behaviour has changed negatively for me

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#193] opened 2018-11-09 15:56 UTC
Things were working normally in the a version but in the most recent b version, keybinds on a dedicated vehicle bar I use are taking priority over my main action bar even when there aren't any buttons on the vehicle bar.  So, when I push 1, it's a blank button on my vehicle bar that's activating, it's not falling back to my action bar.

The actual "priority" keybind setting doesn't appear to have any impact here, I do have that active on the vehicle bar (as I need to in order to ensure that those keybinds are what are used when the vehicle bar is active) but I tried without it with no change.

I've reverted back to the a version for now.

**Comment by brittyazel** [comment] 2018-11-09 16:46
Ok I'll look into this. I have no idea what could have done that, as I only made a couple of totally unrelated changes. Thanks for the heads up

**Comment by pottervogel** [comment] 2018-11-10 12:36
all my keybinds are gone, and keybinding doesn't work any more

**Comment by brittyazel** [comment] 2018-11-10 19:04
Did you /reload before trying to keybind again?

**Comment by brittyazel** [comment] 2018-11-10 19:07
@raysmith, ok I figured out what the issue is. I changed from bars using show/hide for specific states to instead using SetAlpha. This was to avoid taint, but it appears to have issues elsewhere. I'll revert this

**Comment by brittyazel** [comment] 2018-11-10 20:17
@raysmith59 Can you check the MASTER branch and tell me if you still have that issue? I reverted the changes above

**Comment by raysmith59** [comment] 2018-11-10 21:15
Not that issue but only because a new one showed up, now the vehicle bar is "blank" (when I go into edit mode, the only buttons that show up are the ones that already have spells on them that aren't vehicle-specific).  When I did a vehicle quest the buttons didn't show up, either.

**Comment by brittyazel** [comment] 2018-11-10 21:35
Ok can you try that for me please?

Also, how are you keybinding two different buttons to the same key? Usually when you keybind a key that already has a keybind it removes it from the other key

**Comment by brittyazel** [comment] 2018-11-10 21:58
I guess you could set the keybinds on the vehicle bar, lock the keybinds and then give them priority. That might work. Is that how you're doing it?

**Comment by brittyazel** [comment] 2018-11-10 22:05
I'm closing this as I've verified this technique works well. Please report back though with your success

**Closed by brittyazel** 2018-11-10 22:05 UTC

**Comment by raysmith59** [comment] 2018-11-11 02:18
I set the action bars as usual (1-8, etc) and lock them.  I then do the same for the vehicle bar, lock them, then set them as priority.

**Comment by raysmith59** [comment] 2018-11-12 18:51
So far so good with the most recent release, thanks!
