### ISSUE TITLE
Icon selector when editing a button is problematic

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#214] opened 2018-12-16 20:55 UTC
First time I tried it didn't close and has no way to close, had to relog.  Second time it did populate when I selected an icon but the ? option is missing and I think there are other changes vs what I'm used to seeing, just not sure what.

**Comment by brittyazel** [comment] 2019-01-15 00:55
duplicate of #92

**Closed by brittyazel** 2019-01-15 00:55 UTC
